// Generated by CoffeeScript 1.7.1
(function() {
  var Backbone, async, collections, decorate, decorators, ejs, ejslocals, env, fs, helpers, http, initCollections, initDb, mongodb, path, remotecollections, settings, _;

  fs = require('fs');

  _ = require('underscore');

  Backbone = require('backbone4000');

  async = require('async');

  path = require('path');

  helpers = require('helpers');

  decorators = require('decorators2');

  decorate = decorators.decorate;

  http = require('http');

  mongodb = require('mongodb');

  ejs = require('ejs');

  ejslocals = require('ejs-locals');

  collections = require('collections/serverside');

  remotecollections = require('collections-remote/serverside');

  settings = {
    httpport: 3335
  };

  env = {
    settings: settings
  };

  initDb = function(callback) {
    env.db = new mongodb.Db('loclog', new mongodb.Server('localhost', 27017), {
      safe: true
    });
    return env.db.open(callback);
  };

  initCollections = function(callback) {
    return env.points = new collections.MongoCollection({
      db: env.db,
      collection: 'points'
    });
  };

}).call(this);
